### ISSUE TITLE
Visual Studio installation requires degree in rocket science

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#171]
The .vsconfig has things in it unused and unsupported
No guide on installing QT for it
 it asks for QT folder so you have to set that, then asks for QT CMAKE so set that, then asks for QT GUI then set that, then asks for FF7TK then set that, then asked for ZLIB so set that and then complained about the lib so had to use a different zlib and that worked.
 
 
 It's much better for VS to include a project file.

**Comment by myst6re** [comment]
We are still in a transition between a Qt project and a CMake project. Makou Reactor always worked well with Qt Creator IDE, and now it should support Visual Studio Code too. For Visual Studio, we added some configurations to help the setup, but this was not updated for at least a year. None of us use Visual Studio anymore, so I recommend migrate to Visual Studio Code or Qt Creator.

About a project file, if you mean a Visual Studio Project file, I don't think that's a good idea, Makou Reactor is a CMake project because it can be built on Windows, Mac OSX and Linux without proprietary tools.

**Comment by DLPB2** [comment]
Of course it's your choice and design - but I fundamentally disagree with this approach.  No setup should require learning 100 more things to install.  I'm too used to Delphi and Lazarus where there is one compiler, one project file, and it all works - and I can send the folder to someone else as if it's portable (because Delphi projects and exes are).  This just seems like an out of control nonsense - and I don't mean makou here btw - I mean C installations in general.  I've never seen so many options, downloads, add ons, redundant code, exceptions, fixes, work arounds-- and then each time I want to compile a program written in C I have to spend 5 hours just learning about the quirks and add ons and -- then the libs.

I don't know how we got to a point where this is acceptable to programming - but I guess it isn't going to change, so i'll be staying well away from C haha :)  You can close this request.

**Comment by julianxhokaxhiu** [comment]
@DLPB2 if you checkout `develop` now, and follow the relative https://github.com/myst6re/makoureactor/tree/develop#windows instructions you should be able to build Makou just fine. We worked on streamlining this part and now it's super easy. Make sure you close the repository using `git clone --recursive` or if you have it already cloned:
```sh
$ git pull --all
$ git submodule update --init
```
then follow the instructions and you should be good to go!
