### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by TurBoss** [myst6re/makoureactor#6]
I'm interested in translate app to Spanish

now in the develop branch I can only see French language
how to enable the English one

thx

**Comment by TurBoss** [comment]
okay i found it myself

thx

**Comment by sithlord48** [comment]
to get makou working in english you must put the Makou_Reactor.qm file in the same path as the execuitable (or have it in /usr/share/makoureactor/ if makou is installed in /usr/bin/makoureactor)

to enable a new language you must modify the .pro file and add under translations
Makou_Reactor_es.ts the new section would look like 

TRANSLATIONS += Makou_Reactor_en.ts \
    Makou_Reactor_ja.ts \
    Makou_Reactor_es.ts

then you need to run lupdate on the .pro file to generate the ts file.
the ts file can be editing using QT Lingust . later on when the project is build a call will be used by qmake (since we told it to in the pro) it will run lrelease Makou_Reactor.pro and generate the .qm files that will be shiped w/ makou.. makou should auto detect languages so you will not need to change anything in the makou code to see spanish as a choice.

**Comment by TurBoss** [comment]
Oh nice detailed info thank you
