### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by myst6re** [myst6re/makoureactor#71]
See branch feature/appimage2. Travis will deploy a AppImage package for Linux. Other change: at every pushes, a built package will be uploaded on the "continuous" tag.

Pull request #70

**Comment by probonopd** [comment]
:+1: Will the AppImage be available for download on GitHub Releases?

**Comment by sithlord48** [comment]
@probonopd this will be autorelaesd using linuxdeployqt and uploaded as suggested to a taged "continuous". This should function like the other appimages i've made in the past. I think we spoke about his package a few months ago its just taken sometime for merging to happen.

@myst6re please see my one comment on the travis file we need to change the upload of *.Appimage to Makou*.Appimage* so that we dont release the linuxdeployqt.Appimage we downloaded to make ours.

**Comment by probonopd** [comment]
> @probonopd this will be autorelaesd using linuxdeployqt and uploaded as suggested to a taged "continuous"

Thank you. Do you have an ETA for this to happen?

**Comment by probonopd** [comment]
Most likely due to the desktop file not passing `desktop-file-validate`:
https://travis-ci.org/myst6re/makoureactor/jobs/323231778#L1421

**Comment by sithlord48** [comment]
Fixed in Develop (finally)
